#!/bin/bash
SERVER_PROPERTIES=server.properties
MINECRAFT_SERVER_JAR=minecraft_server.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$MINECRAFT_SERVER_JAR" ]; then
	wget "https://s3.amazonaws.com/Minecraft.Download/versions/1.8/minecraft_server.1.8.jar" -O $MINECRAFT_SERVER_JAR
fi

